version: "3.10"

services:
  backend:
    build:
      context: .
      dockerfile: ml_backend/Dockerfile
    image: backend:latest
    ports:
      - 8080:8080
    networks:
      - project_network
networks:
  project_network: